const components=[
['button','CMP-0001','Button'],['text-field','CMP-0002','TextField'],['checkbox','CMP-0003','Checkbox'],['radio','CMP-0004','Radio'],['select-combobox','CMP-0005','Select/Combobox'],['link','CMP-0006','Link'],['alert-status','CMP-0007','Alert/Status'],['modal-dialog','CMP-0008','Modal/Dialog'],['loading-progress','CMP-0009','Loading/Progress'],['card-interativo','CMP-0010','Card interativo'],['pagination','CMP-0011','Pagination'],['toast','CMP-0012','Toast'],['tabs','CMP-0013','Tabs'],['accordion','CMP-0014','Accordion'],['menu','CMP-0015','Menu'],['breadcrumb','CMP-0016','Breadcrumb'],['tooltip','CMP-0017','Tooltip'],['bottom-sheet','CMP-0018','Bottom Sheet'],['date-picker','CMP-0019','Date Picker'],['file-upload','CMP-0020','File Upload'],['search','CMP-0021','Search'],['autocomplete','CMP-0022','Autocomplete']];

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>document.querySelector('[data-component]')?.dataset.component;
const meta=slug=>components.find(c=>c[0]===slug);
const repositoryComponent=slug=>({'card-interativo':'interactive-card'}[slug]||slug);
const primaryWebSource=slug=>({'select-combobox':'select.css'}[slug]||`${repositoryComponent(slug)}.css`);
const githubFileUrl=path=>`https://github.com/CIATA-BR/CIATA-DS/blob/main/${path}`;

function demoMarkup(slug){
 switch(slug){
  case 'button':return '<button type="button" id="primary">Salvar alterações</button> <button type="button" disabled>Indisponível</button>';
  case 'text-field':return '<label for="name">Nome completo</label><input id="name" type="text" autocomplete="name"><p id="name-help">Digite como consta no documento.</p>';
  case 'checkbox':return '<label><input type="checkbox"> Receber atualizações por e-mail</label>';
  case 'radio':return '<fieldset><legend>Forma de contato</legend><label><input type="radio" name="contact" value="email"> E-mail</label><br><label><input type="radio" name="contact" value="phone"> Telefone</label></fieldset>';
  case 'select-combobox':return '<label for="state">Estado</label><select id="state"><option value="">Selecione</option><option>São Paulo</option><option>Pará</option><option>Minas Gerais</option></select>';
  case 'link':return '<p><a href="../">Voltar ao índice do Test Lab</a></p><p><a href="https://github.com/CIATA-BR/CIATA-DS">Abrir repositório CIATA-DS</a></p>';
  case 'alert-status':return '<div class="status" role="status">Preferências salvas com sucesso.</div><div class="status" role="alert">Não foi possível concluir a operação.</div>';
  case 'modal-dialog':return '<button id="open-dialog" type="button">Abrir diálogo</button><div id="dialog-backdrop" class="dialog-backdrop" hidden><div class="dialog-surface" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title" tabindex="-1">Confirmar ação</h2><p>Este diálogo testa foco inicial, contenção e retorno de foco.</p><button id="close-dialog" type="button">Fechar</button></div></div>';
  case 'loading-progress':return '<div class="progress-wrap"><label for="progress">Processando arquivos</label><progress id="progress" max="100" value="45">45%</progress><p>45% concluído</p></div>';
  case 'card-interativo':return '<article class="panel"><h2><a href="../button/">Revisar componente Button</a></h2><p>Um card com uma única ação principal representada por link nativo.</p></article>';
  case 'pagination':return '<nav aria-label="Paginação"><a href="#page1" aria-current="page">1</a> <a href="#page2">2</a> <a href="#page3">3</a> <a href="#next">Próxima</a></nav>';
  case 'toast':return '<button id="show-toast" type="button">Mostrar notificação</button><div id="toast" class="toast" role="status" hidden>Arquivo enviado com sucesso.</div>';
  case 'tabs':return '<div class="tablist" role="tablist" aria-label="Informações do projeto"><button role="tab" id="tab-overview" aria-controls="panel-overview" aria-selected="true" tabindex="0">Visão geral</button><button role="tab" id="tab-a11y" aria-controls="panel-a11y" aria-selected="false" tabindex="-1">Acessibilidade</button></div><section id="panel-overview" role="tabpanel" aria-labelledby="tab-overview" tabindex="0"><p>Conteúdo da visão geral.</p></section><section id="panel-a11y" role="tabpanel" aria-labelledby="tab-a11y" tabindex="0" hidden><p>Conteúdo de acessibilidade.</p></section>';
  case 'accordion':return '<details><summary>O que será validado?</summary><p>Nome, estado expandido, teclado, foco e leitura do conteúdo.</p></details><details><summary>Qual leitor de tela usar?</summary><p>Registre o leitor, versão, navegador e sistema operacional.</p></details>';
  case 'menu':return '<button id="menu-trigger" type="button" aria-haspopup="menu" aria-expanded="false">Ações</button><div id="menu" class="menu" role="menu" hidden><button role="menuitem" type="button">Editar</button><button role="menuitem" type="button">Duplicar</button><button role="menuitem" type="button">Excluir</button></div>';
  case 'breadcrumb':return '<nav class="breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="../">Test Lab</a></li><li><a href="../">Componentes</a></li><li aria-current="page">Breadcrumb</li></ol></nav>';
  case 'tooltip':return '<button id="tip-trigger" type="button" aria-describedby="tip">Ajuda sobre atalhos</button><span id="tip" role="tooltip" class="tooltip" hidden>Use Tab para avançar e Shift+Tab para voltar.</span>';
  case 'bottom-sheet':return '<button id="open-sheet" type="button">Abrir filtros</button><section id="sheet" class="bottom-sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title" hidden><h2 id="sheet-title" tabindex="-1">Filtros</h2><label><input type="checkbox"> Somente componentes experimentais</label><p><button id="close-sheet" type="button">Fechar</button></p></section>';
  case 'date-picker':return '<label for="date">Data de nascimento</label><input id="date" type="date" min="1900-01-01" max="2026-12-31">';
  case 'file-upload':return '<label for="file">Selecionar documento</label><input id="file" type="file" multiple><p id="file-status" role="status">Nenhum arquivo selecionado.</p>';
  case 'search':return '<form role="search" id="search-form"><label for="q">Buscar componentes</label><div class="row"><input id="q" type="search"><button type="submit">Buscar</button></div><p id="search-status" role="status"></p></form>';
  case 'autocomplete':return '<label for="city">Cidade</label><input id="city" type="text" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="city-list" autocomplete="off"><ul id="city-list" role="listbox" hidden><li role="option" id="city-sp">São Paulo</li><li role="option" id="city-stm">Santarém</li><li role="option" id="city-bh">Belo Horizonte</li></ul><p id="auto-status" role="status"></p>';
  default:return '<p>Exemplo interativo em preparação.</p>';
 }
}

function wire(slug){
 if(slug==='modal-dialog'){const o=document.querySelector('#open-dialog'),b=document.querySelector('#dialog-backdrop'),c=document.querySelector('#close-dialog'),t=document.querySelector('#dialog-title');const close=()=>{b.hidden=true;o.focus()};o.onclick=()=>{b.hidden=false;t.focus()};c.onclick=close;document.addEventListener('keydown',e=>{if(!b.hidden&&e.key==='Escape'){e.preventDefault();close()}})}
 if(slug==='toast'){const btn=document.querySelector('#show-toast'),toast=document.querySelector('#toast');btn.onclick=()=>{toast.hidden=false;setTimeout(()=>toast.hidden=true,4000)}}
 if(slug==='tabs'){const tabs=[...document.querySelectorAll('[role=tab]')];tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectTab(i));tab.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const n=e.key==='ArrowRight'?(i+1)%tabs.length:(i-1+tabs.length)%tabs.length;selectTab(n);tabs[n].focus()})});function selectTab(i){tabs.forEach((t,j)=>{const p=document.getElementById(t.getAttribute('aria-controls'));t.setAttribute('aria-selected',String(i===j));t.tabIndex=i===j?0:-1;p.hidden=i!==j})}}
 if(slug==='menu'){const t=document.querySelector('#menu-trigger'),m=document.querySelector('#menu');t.onclick=()=>{const open=m.hidden;m.hidden=!open;t.setAttribute('aria-expanded',String(open));if(open)m.querySelector('[role=menuitem]').focus()};document.addEventListener('keydown',e=>{if(!m.hidden&&e.key==='Escape'){m.hidden=true;t.setAttribute('aria-expanded','false');t.focus()}})}
 if(slug==='tooltip'){const t=document.querySelector('#tip-trigger'),tip=document.querySelector('#tip');const show=()=>tip.hidden=false,hide=()=>tip.hidden=true;t.addEventListener('focus',show);t.addEventListener('mouseenter',show);t.addEventListener('blur',hide);t.addEventListener('mouseleave',hide);t.addEventListener('keydown',e=>{if(e.key==='Escape')hide()})}
 if(slug==='bottom-sheet'){const o=document.querySelector('#open-sheet'),s=document.querySelector('#sheet'),c=document.querySelector('#close-sheet'),h=document.querySelector('#sheet-title');const close=()=>{s.hidden=true;o.focus()};o.onclick=()=>{s.hidden=false;h.focus()};c.onclick=close;document.addEventListener('keydown',e=>{if(!s.hidden&&e.key==='Escape'){e.preventDefault();close()}})}
 if(slug==='file-upload'){const f=document.querySelector('#file'),s=document.querySelector('#file-status');f.onchange=()=>s.textContent=f.files.length?`${f.files.length} arquivo(s) selecionado(s).`:'Nenhum arquivo selecionado.'}
 if(slug==='search'){const f=document.querySelector('#search-form'),q=document.querySelector('#q'),s=document.querySelector('#search-status');f.onsubmit=e=>{e.preventDefault();s.textContent=q.value.trim()?`Busca enviada para “${q.value.trim()}”.`:'Digite um termo para buscar.'}}
 if(slug==='autocomplete'){const input=document.querySelector('#city'),list=document.querySelector('#city-list'),status=document.querySelector('#auto-status'),opts=[...list.querySelectorAll('[role=option]')];let active=-1;const update=()=>{const q=input.value.trim().toLocaleLowerCase('pt-BR');let shown=0;opts.forEach(o=>{o.hidden=!q||!o.textContent.toLocaleLowerCase('pt-BR').includes(q);if(!o.hidden)shown++});list.hidden=shown===0;input.setAttribute('aria-expanded',String(shown>0));status.textContent=q?`${shown} sugestão(ões) disponível(is).`:'';active=-1;input.removeAttribute('aria-activedescendant')};input.addEventListener('input',update);input.addEventListener('keydown',e=>{const visible=opts.filter(o=>!o.hidden);if(!visible.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();active=e.key==='ArrowDown'?(active+1)%visible.length:(active-1+visible.length)%visible.length;input.setAttribute('aria-activedescendant',visible[active].id)}else if(e.key==='Enter'&&active>=0){e.preventDefault();input.value=visible[active].textContent;list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');status.textContent=`${input.value} selecionada.`}else if(e.key==='Escape'){list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant')}});opts.forEach(o=>o.addEventListener('click',()=>{input.value=o.textContent;list.hidden=true;input.setAttribute('aria-expanded','false');status.textContent=`${input.value} selecionada.`;input.focus()}))}
}

function renderIndex(){const list=document.querySelector('#component-list');if(!list)return;list.innerHTML=components.map(([slug,id,name])=>`<li><a href="./${slug}/"><strong>${id}</strong><br>${esc(name)}</a></li>`).join('')}
function renderComponent(){const slug=current();if(!slug)return;const m=meta(slug);if(!m)return;const repoComponent=repositoryComponent(slug);const sourcePath=`components/${repoComponent}/web/${primaryWebSource(slug)}`;document.title=`${m[1]} — ${m[2]} — CIATA Accessibility Test Lab`;document.querySelector('#component-title').textContent=`${m[1]} — ${m[2]}`;document.querySelector('#demo').innerHTML=demoMarkup(slug);document.querySelector('#spec-link').href=githubFileUrl(`components/${repoComponent}/spec.md`);document.querySelector('#matrix-link').href=githubFileUrl(`components/${repoComponent}/validation-matrix.md`);const sourceLink=document.querySelector('#source-link');sourceLink.href=githubFileUrl(sourcePath);sourceLink.textContent=`Código do componente — ${sourcePath}`;wire(slug)}
renderIndex();renderComponent();